#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Nov  2 09:30:52 2020

@author: piaoruilin
"""

import numpy as np

data = np.random.choice(10, 100)

data = data.reshape(20,5)

data[3,:] = 0
data[7,:] = 0
data[8,:] = 0
data[14,:] = 0
data[17,:] = 0

print(data)
print('original data shape', data.shape)

print('----- after removing rows with only 0 -----')

data = data[~np.all(data == 0, axis=1)]

print(data)
print('new data shape', data.shape)