#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 31 17:57:31 2020

@author: piaoruilin
"""

import csv

#============================================================================================================================
cancer_list = "/Users/piaoruilin/Desktop/python/Hackathon Data - Cancer Symptom.csv"
drugs_list = "/Users/piaoruilin/Desktop/python/Hackathon Data - Drug Symptom-2.csv"
others_list = "/Users/piaoruilin/Desktop/python/Hackathon Data - Other Symptom.csv"
    
symptom_list, description_list = ([] for i in range(2)) #SYMPTOM
cancer_area_list, cancer_symptom_list,cancer_description_list,cancer_fatal_freq = ([] for i in range(4)) #CANCER
cancer_area_drug_list,cancer_type_list,drug_name_list,drug_symptom_list,drug_description_list = ([] for i in range(5)) #CANCERFREQ
drug_normal_freq_list,drug_fatal_freqeuncy_list,drug_emergency_freq_list,drug_fatal_simul_list = ([] for i in range(4)) #DRUG
other_symptom_list,other_description_list,other_fatal_freq_list = ([] for i in range(3)) #OTHER
    
def open_sort_csv(c,d,e):

    #CANCER
    with open(str(c), newline='') as cancerchart:
        reader = csv.reader(cancerchart)
        cancer_csv = [tuple(row) for row in reader] 
        

    for i in range(len(cancer_csv)):
        cancer_area_list.append(cancer_csv[i][0])
        cancer_symptom_list.append(cancer_csv[i][1])
        cancer_description_list.append(cancer_csv[i][2])
        cancer_fatal_freq.append(cancer_csv[i][3])

    #DRUG
    with open(str(d), newline='') as f:  
        reader = csv.reader(f)
        drug_csv = [tuple(row) for row in reader]
        

    for i in range(len(drug_csv)):
        cancer_area_drug_list.append(drug_csv[i][0])
        cancer_type_list.append(drug_csv[i][1])
        drug_name_list.append(drug_csv[i][2])
        drug_symptom_list.append(drug_csv[i][3])
        drug_description_list.append(drug_csv[i][4])
        drug_normal_freq_list.append(drug_csv[i][5])
        drug_fatal_freqeuncy_list.append(drug_csv[i][6])
        drug_emergency_freq_list.append(drug_csv[i][7])
        
    #OTHER
    with open(str(e), newline='') as otherchart:
        reader = csv.reader(otherchart)
        other_csv = [tuple(row) for row in reader]
        
 #compare 
    for i in range(len(other_csv)):
        other_symptom_list.append(other_csv[i][0])
        other_description_list.append(other_csv[i][1])
        other_fatal_freq_list.append(other_csv[i][2])
    return(symptom_list,description_list,cancer_area_list,cancer_symptom_list,cancer_description_list,cancer_fatal_freq,cancer_area_drug_list,cancer_type_list,drug_name_list,drug_symptom_list,drug_description_list,drug_normal_freq_list,drug_fatal_freqeuncy_list,drug_emergency_freq_list,drug_fatal_simul_list)

open_sort_csv(cancer_list,drugs_list,others_list)
print(symptom_list,description_list,cancer_area_list,cancer_symptom_list,cancer_description_list,cancer_fatal_freq,cancer_area_drug_list,cancer_type_list,drug_name_list,drug_symptom_list,drug_description_list,drug_normal_freq_list,drug_fatal_freqeuncy_list,drug_emergency_freq_list,drug_fatal_simul_list)