#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Oct 31 18:19:38 2020

@author: piaoruilin
"""
import csv
from collections import defaultdict

columns = defaultdict(list)
with open('/Users/piaoruilin/Desktop/python/Hackathon Data - Cancer Symptom.csv', 'r') as f:
    reader = csv.reader(f, delimiter=',')
    headers = next(reader)
    column_nums = range(len(headers)) # Do NOT change to xrange
    for row in reader:
        for i in column_nums:
            columns[headers[i]].append(row[i])
# Following line is only necessary if you want a key error for invalid column names
columns = dict(columns)

print(columns)