#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Oct 29 16:34:03 2020

@author: piaoruilin
"""
list1 = [1,1,1,0,0,1]
list2 = [0,0,1,1,0,1]
total = []
final = [total]
num=0

def remove_element(a,b,c) :
    